const mongoose = require('mongoose');
const dotenv = require('dotenv');
const bcrypt = require('bcryptjs');
const User = require('./src/models/User');
const Product = require('./src/models/Product');
const Order = require('./src/models/Order');

dotenv.config();

mongoose.connect(process.env.MONGO_URI);

const importData = async () => {
  try {
    await Order.deleteMany();
    await Product.deleteMany();
    await User.deleteMany();

    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash('password', salt);

    const createdUsers = await User.insertMany([
      { name: 'Admin User', email: 'admin@example.com', password: hashedPassword, role: 'admin' },
      { name: 'Tech Vendor', email: 'vendor1@example.com', password: hashedPassword, role: 'vendor' },
      { name: 'Fashion Vendor', email: 'vendor2@example.com', password: hashedPassword, role: 'vendor' },
      { name: 'John Customer', email: 'customer@example.com', password: hashedPassword, role: 'customer' },
    ]);

    const vendor1Id = createdUsers[1]._id; // Tech / Home & Living
    const vendor2Id = createdUsers[2]._id; // Fashion / Sports / Wellness

    const sampleProducts = [
      // ==========================================
      // ELECTRONICS (11 Products)
      // ==========================================
      {
        name: 'Studio Pro Active ANC Headphones',
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=800',
        description: 'Experience studio-quality sound with hybrid active noise cancellation, ambient awareness, and up to 40 hours of continuous battery life.',
        category: 'Electronics',
        price: 299.99,
        stock: 25,
        rating: 4.8,
        numReviews: 124,
        user: vendor1Id,
      },
      {
        name: 'Epoch CNC Machined Mechanical Keyboard',
        image: 'https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&q=80&w=800',
        description: 'A premium, hot-swappable mechanical keyboard featuring a solid aluminum plate, custom-tuned switches, and RGB ambient base-lighting.',
        category: 'Electronics',
        price: 189.99,
        stock: 12,
        rating: 4.9,
        numReviews: 89,
        user: vendor1Id,
      },
      {
        name: 'Premium Leather Smart Watch Pro',
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800',
        description: 'An elegant timepiece combining mechanical style with a high-res AMOLED display, heart rate monitor, sleep tracking, and a full grain leather band.',
        category: 'Electronics',
        price: 249.50,
        stock: 15,
        rating: 4.5,
        numReviews: 56,
        user: vendor1Id,
      },
      {
        name: 'MagStream Triple Wireless Charger',
        image: 'https://images.unsplash.com/photo-1586816879360-004f5b0c51e3?auto=format&fit=crop&q=80&w=800',
        description: 'Simultaneously fast-charge your smartphone, wireless earbuds, and smartwatch on a beautifully crafted glass and aluminum stand.',
        category: 'Electronics',
        price: 89.99,
        stock: 100,
        rating: 4.6,
        numReviews: 310,
        user: vendor1Id,
      },
      {
        name: 'Quantum Ultra-Wide Curved Monitor',
        image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&q=80&w=800',
        description: 'Immerse yourself in work or play with this breathtaking 34-inch 144Hz curved QLED monitor featuring perfect color accuracy and HDR1000.',
        category: 'Electronics',
        price: 799.00,
        stock: 8,
        rating: 4.8,
        numReviews: 42,
        user: vendor1Id,
      },
      {
        name: 'AcousticFlow Portable Bluetooth Speaker',
        image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&q=80&w=800',
        description: 'IPX7 waterproof wireless speaker delivering booming 360-degree high-fidelity audio with deep bass and interactive LED beat indicators.',
        category: 'Electronics',
        price: 119.99,
        stock: 40,
        rating: 4.4,
        numReviews: 78,
        user: vendor1Id,
      },
      {
        name: 'Ergonomic Vertical Wireless Mouse',
        image: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=800',
        description: 'Promotes an ergonomic, comfortable handshake wrist position to eliminate muscle fatigue. Precision tracking and multi-device connection.',
        category: 'Electronics',
        price: 79.99,
        stock: 65,
        rating: 4.7,
        numReviews: 102,
        user: vendor1Id,
      },
      {
        name: 'Retro Walnut Wooden Turntable',
        image: 'https://images.unsplash.com/photo-1539635278303-d4002c07eae3?auto=format&fit=crop&q=80&w=800',
        description: 'Exquisite hand-polished walnut casing with a high-fidelity carbon fiber tonearm, audio-technica cartridge, and modern Bluetooth output.',
        category: 'Electronics',
        price: 220.00,
        stock: 10,
        rating: 4.8,
        numReviews: 34,
        user: vendor1Id,
      },
      {
        name: 'Smart Ambient Assistant Hub',
        image: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&q=80&w=800',
        description: 'Voice-controlled assistant hub with integrated smart zigbee antenna, premium fabric surround, and an elegant glowing clock screen.',
        category: 'Electronics',
        price: 99.99,
        stock: 50,
        rating: 4.3,
        numReviews: 115,
        user: vendor1Id,
      },
      {
        name: 'Professional Studio Condenser Mic',
        image: 'https://images.unsplash.com/photo-1590608897129-79da98d15969?auto=format&fit=crop&q=80&w=800',
        description: 'Broadcast-grade studio cardioid microphone designed for high-resolution vocal recording, podcasting, and gaming streams.',
        category: 'Electronics',
        price: 149.00,
        stock: 20,
        rating: 4.9,
        numReviews: 47,
        user: vendor1Id,
      },
      {
        name: 'Professional 4K DSLR Camera Set',
        image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=800',
        description: 'Capture world-class details with our high-end 24.2MP mirrorless sensor. Bundle includes an EF 24-105mm ultra-stabilized lens.',
        category: 'Electronics',
        price: 1399.99,
        stock: 5,
        rating: 5.0,
        numReviews: 16,
        user: vendor1Id,
      },

      // ==========================================
      // FASHION & APPAREL (11 Products)
      // ==========================================
      {
        name: 'Classic Denim Trucker Jacket',
        image: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&q=80&w=800',
        description: 'A timeless silhouette crafted from thick, organic denim cotton. Gets better with age and features double chest button pockets.',
        category: 'Fashion',
        price: 89.99,
        stock: 30,
        rating: 4.6,
        numReviews: 42,
        user: vendor2Id,
      },
      {
        name: 'Vintage Aviator Polarized Sunglasses',
        image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&q=80&w=800',
        description: 'Iconic golden frame aviator sunglasses featuring polarized TAC lenses with 100% UV400 protective coating.',
        category: 'Fashion',
        price: 145.00,
        stock: 12,
        rating: 4.8,
        numReviews: 19,
        user: vendor2Id,
      },
      {
        name: 'Canvas Weekender Travel Duffel',
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800',
        description: 'A spacious and highly durable water-resistant canvas duffel detailed with full-grain leather straps and heavy brass zippers.',
        category: 'Fashion',
        price: 110.00,
        stock: 25,
        rating: 4.4,
        numReviews: 76,
        user: vendor2Id,
      },
      {
        name: 'Obsidian Tailored Trench Coat',
        image: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&q=80&w=800',
        description: 'A beautifully structured, windproof luxury trench coat designed with a double-breasted closure and adjustable waist belt.',
        category: 'Fashion',
        price: 199.99,
        stock: 14,
        rating: 4.9,
        numReviews: 28,
        user: vendor2Id,
      },
      {
        name: 'Linen Casual Collared Button-Down',
        image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&q=80&w=800',
        description: 'Tailored from 100% breathable organic Belgian flax linen. Perfect for styling a smart-casual beach or office look.',
        category: 'Fashion',
        price: 65.00,
        stock: 40,
        rating: 4.5,
        numReviews: 53,
        user: vendor2Id,
      },
      {
        name: 'Merino Wool Minimalist Sweater',
        image: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&q=80&w=800',
        description: 'Woven from exceptionally soft, ultra-fine Merino wool. Features natural odor resistance and thermoregulating properties.',
        category: 'Fashion',
        price: 95.00,
        stock: 35,
        rating: 4.7,
        numReviews: 61,
        user: vendor2Id,
      },
      {
        name: 'Nomad Classic Leather Chelsea Boots',
        image: 'https://images.unsplash.com/photo-1638247025967-b4e38f787b76?auto=format&fit=crop&q=80&w=800',
        description: 'Exquisite pull-up Italian leather Chelsea boots equipped with comfortable elastic side gores and a Goodyear welted rubber sole.',
        category: 'Fashion',
        price: 180.00,
        stock: 15,
        rating: 4.8,
        numReviews: 44,
        user: vendor2Id,
      },
      {
        name: 'Waterproof Shield Shell Parka',
        image: 'https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&q=80&w=800',
        description: 'Fully seam-sealed waterproof outer jacket. Highly breathable with multiple hidden utility pockets and adjustable storm hood.',
        category: 'Fashion',
        price: 220.00,
        stock: 18,
        rating: 4.6,
        numReviews: 32,
        user: vendor2Id,
      },
      {
        name: 'Gold Hexagon Chain Pendant',
        image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=800',
        description: 'A minimalist 18k gold-plated solid silver pendant featuring an architectural hexagon prism charm. Hypoallergenic design.',
        category: 'Fashion',
        price: 125.00,
        stock: 10,
        rating: 4.7,
        numReviews: 19,
        user: vendor2Id,
      },
      {
        name: 'Premium Suede Crossbody Bag',
        image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&q=80&w=800',
        description: 'Designed in Paris, this gorgeous suede shoulder bag features detailed golden hardware, dynamic chain drop, and magnetic clasp.',
        category: 'Fashion',
        price: 135.00,
        stock: 22,
        rating: 4.5,
        numReviews: 29,
        user: vendor2Id,
      },

      // ==========================================
      // HOME & LIVING (10 Products)
      // ==========================================
      {
        name: 'Aether Ergonomic Office Chair',
        image: 'https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?auto=format&fit=crop&q=80&w=800',
        description: 'Work in perfect comfort with state-of-the-art lumbar adaptive support, 3D armrests, and dynamic micro-mesh breathability.',
        category: 'Home & Living',
        price: 349.99,
        stock: 10,
        rating: 4.7,
        numReviews: 231,
        user: vendor1Id,
      },
      {
        name: 'Terrene Ceramic Coffee Mug Set',
        image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&q=80&w=800',
        description: 'Elevate your daily brew. Hand-spun organic ceramic mug set featuring beautiful speckled earthy tones. Microwave & dishwasher safe.',
        category: 'Home & Living',
        price: 24.99,
        stock: 50,
        rating: 4.9,
        numReviews: 12,
        user: vendor1Id,
      },
      {
        name: 'Solid Oak Modular Desk Organizer',
        image: 'https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?auto=format&fit=crop&q=80&w=800',
        description: 'Keep your tabletop neat with modular slots, pen blocks, magnetic clip bowls, and phone easel carved from a single piece of premium white oak.',
        category: 'Home & Living',
        price: 45.00,
        stock: 40,
        rating: 4.6,
        numReviews: 87,
        user: vendor1Id,
      },
      {
        name: 'Eclipse Smart Ambient Table Lamp',
        image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&q=80&w=800',
        description: 'Sculptural desk lamp casting soft, indirect ambient light. Compatible with smart home controls and features full custom-hue lighting.',
        category: 'Home & Living',
        price: 79.99,
        stock: 30,
        rating: 4.5,
        numReviews: 64,
        user: vendor1Id,
      },
      {
        name: 'Solitude Acoustic Desk Divider',
        image: 'https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?auto=format&fit=crop&q=80&w=800',
        description: 'Dampens background office noise and marks physical boundary. Crafted from high-density eco-felt wool fibers.',
        category: 'Home & Living',
        price: 60.00,
        stock: 15,
        rating: 4.3,
        numReviews: 24,
        user: vendor1Id,
      },
      {
        name: 'Stainless Steel Insulated French Press',
        image: 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&q=80&w=800',
        description: 'Double-walled vacuum seal keeps coffee piping hot for hours. Integrated micro-filter plunger keeps sediment out of your cup.',
        category: 'Home & Living',
        price: 39.99,
        stock: 80,
        rating: 4.8,
        numReviews: 150,
        user: vendor1Id,
      },
      {
        name: 'Minimalist Earth Speckled Planter',
        image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&q=80&w=800',
        description: 'Premium ceramic table planter detailed with raw textured exterior and a subtle drainage tray. Perfect for small indoor succulents.',
        category: 'Home & Living',
        price: 35.00,
        stock: 45,
        rating: 4.7,
        numReviews: 31,
        user: vendor1Id,
      },
      {
        name: 'Luxury Scented Soy Candle Set',
        image: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&q=80&w=800',
        description: 'Three custom fragrances: Sandalwood, Lavender Tea, and Amber Bark. Made with clean-burning soy wax and crackling wood wicks.',
        category: 'Home & Living',
        price: 48.00,
        stock: 60,
        rating: 4.9,
        numReviews: 73,
        user: vendor1Id,
      },
      {
        name: 'Hand-Woven Nordic Wool Rug',
        image: 'https://images.unsplash.com/photo-1600121848594-d8644e57abab?auto=format&fit=crop&q=80&w=800',
        description: 'Plush, geometric accent area rug hand-woven by local artisans. Adds soft, warm texture and cozy Scandinavian vibes to any room.',
        category: 'Home & Living',
        price: 280.00,
        stock: 6,
        rating: 4.8,
        numReviews: 18,
        user: vendor1Id,
      },
      {
        name: 'Organic Stoneware Dinner Plate Set',
        image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&q=80&w=800',
        description: 'Set of 4 hand-glazed durable stoneware dinner plates. Each piece boasts slightly unique shapes and premium organic charm.',
        category: 'Home & Living',
        price: 85.00,
        stock: 20,
        rating: 4.6,
        numReviews: 15,
        user: vendor1Id,
      },

      // ==========================================
      // SPORTS & OUTDOORS (10 Products)
      // ==========================================
      {
        name: 'HydroFlow Insulated Steel Flask',
        image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&q=80&w=800',
        description: 'Keep drinks ice cold for 24 hours or steaming hot for 12. Double-wall stainless steel with premium slip-free powder coating.',
        category: 'Sports & Outdoors',
        price: 35.00,
        stock: 120,
        rating: 4.8,
        numReviews: 188,
        user: vendor2Id,
      },
      {
        name: 'Zenith Smart Fitness Activity Ring',
        image: 'https://images.unsplash.com/photo-1617042375876-a13e36732a04?auto=format&fit=crop&q=80&w=800',
        description: 'Ultra-light titanium smart ring tracking sleep, HRV, body temperature, and workouts with seamless cloud analytics.',
        category: 'Sports & Outdoors',
        price: 299.00,
        stock: 15,
        rating: 4.7,
        numReviews: 43,
        user: vendor2Id,
      },
      {
        name: 'Apex Grip Natural Rubber Yoga Mat',
        image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&q=80&w=800',
        description: 'Provides absolute grip even during sweaty hot yoga sessions. 5mm thickness protects joints while keeping you perfectly stable.',
        category: 'Sports & Outdoors',
        price: 75.00,
        stock: 50,
        rating: 4.9,
        numReviews: 67,
        user: vendor2Id,
      },
      {
        name: 'Solitude Lightweight Camping Hammock',
        image: 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&q=80&w=800',
        description: 'Spacious nylon camping hammock. Packs down into an integrated pocket, ideal for quick weekend trail breaks.',
        category: 'Sports & Outdoors',
        price: 45.00,
        stock: 90,
        rating: 4.6,
        numReviews: 29,
        user: vendor2Id,
      },
      {
        name: 'Expedition Trail Waterproof Backpack',
        image: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&q=80&w=800',
        description: 'Premium ripstop polyester mountain backpack. Includes dynamic load distribution, ergonomic hips harness, and full rain guard.',
        category: 'Sports & Outdoors',
        price: 129.99,
        stock: 25,
        rating: 4.8,
        numReviews: 54,
        user: vendor2Id,
      },
      {
        name: 'Hex Pro Steel Adjustable Dumbbells',
        image: 'https://images.unsplash.com/photo-1638536532686-d610adfc8e5c?auto=format&fit=crop&q=80&w=800',
        description: 'Quick-adjust dial changes weights instantly. Replaces 10 individual weight blocks, taking up minimal space in your home gym.',
        category: 'Sports & Outdoors',
        price: 249.99,
        stock: 12,
        rating: 4.7,
        numReviews: 81,
        user: vendor2Id,
      },
      {
        name: 'Summit Heavy-Duty Folding Camp Chair',
        image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&q=80&w=800',
        description: 'Extremely rugged aircraft-grade aluminum legs supporting up to 350lbs. Comfortable mesh fabric with cup holder pockets.',
        category: 'Sports & Outdoors',
        price: 59.99,
        stock: 40,
        rating: 4.5,
        numReviews: 33,
        user: vendor2Id,
      },
      {
        name: 'High-Velocity Bearing Jump Rope',
        image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=800',
        description: 'High-speed 360-degree double ball bearing cord for fast-cadence jump training. Weighted non-slip comfortable grip handles.',
        category: 'Sports & Outdoors',
        price: 25.00,
        stock: 150,
        rating: 4.4,
        numReviews: 92,
        user: vendor2Id,
      },
      {
        name: 'Trailhead GPS Outdoor Smart Watch',
        image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&q=80&w=800',
        description: 'Tough, shock-resistant tactical outdoor watch featuring altimeter, barometer, compass, topographic maps, and satellite navigation.',
        category: 'Sports & Outdoors',
        price: 279.99,
        stock: 20,
        rating: 4.6,
        numReviews: 48,
        user: vendor2Id,
      },
      {
        name: 'Compact Telescopic Carbon Trekking Poles',
        image: 'https://images.unsplash.com/photo-1595152772835-219674b2a8a6?auto=format&fit=crop&q=80&w=800',
        description: 'Carbon fiber poles designed to dampen trail vibration. Quick-flip locks for easy length adjustment. Comfortable cork grips.',
        category: 'Sports & Outdoors',
        price: 69.99,
        stock: 35,
        rating: 4.8,
        numReviews: 22,
        user: vendor2Id,
      },

      // ==========================================
      // WELLNESS & BEAUTY (10 Products)
      // ==========================================
      {
        name: 'AromaTherapy Ultrasonic Diffuser',
        image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&q=80&w=800',
        description: 'Beautiful real hand-crafted porcelain shell diffuser emitting micro-mist. Features quiet operation and warm ambient glow timer.',
        category: 'Wellness & Beauty',
        price: 55.00,
        stock: 30,
        rating: 4.9,
        numReviews: 95,
        user: vendor2Id,
      },
      {
        name: 'Botanica Organic Rosewood Skincare Set',
        image: 'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&q=80&w=800',
        description: 'Three step glow routine containing organic rose water mist, revitalizing vitamin C facial serum, and lightweight hydration lotion.',
        category: 'Wellness & Beauty',
        price: 145.00,
        stock: 15,
        rating: 4.8,
        numReviews: 41,
        user: vendor2Id,
      },
      {
        name: 'Weighted Bamboo Comfort Sleep Mask',
        image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&q=80&w=800',
        description: 'Filled with micro-glass beads to deliver soothing deep pressure stimulation. Wrapped in luxurious, cooling bamboo fabric.',
        category: 'Wellness & Beauty',
        price: 29.99,
        stock: 100,
        rating: 4.7,
        numReviews: 122,
        user: vendor2Id,
      },
      {
        name: 'Organic Chamomile Sleep Tea Bundle',
        image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=800',
        description: 'A soothing evening loose-leaf tea collection with whole flower organic Chamomile, lavender sprigs, and refreshing valerian root.',
        category: 'Wellness & Beauty',
        price: 35.00,
        stock: 200,
        rating: 4.9,
        numReviews: 64,
        user: vendor2Id,
      },
      {
        name: 'Pure Dead Sea Mineral Bath Salts',
        image: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&q=80&w=800',
        description: '100% natural, unrefined Dead Sea crystals packed with minerals to soothe tired muscles and restore natural skin hydration.',
        category: 'Wellness & Beauty',
        price: 24.99,
        stock: 80,
        rating: 4.8,
        numReviews: 53,
        user: vendor2Id,
      },
      {
        name: 'Rose Quartz Facial Roller & Gua Sha Set',
        image: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&q=80&w=800',
        description: 'Improves blood circulation and promotes lymphatic drainage. Made with hand-carved natural Brazilian pink rose quartz stone.',
        category: 'Wellness & Beauty',
        price: 32.00,
        stock: 45,
        rating: 4.6,
        numReviews: 38,
        user: vendor2Id,
      },
      {
        name: 'Sonic Bamboo Smart Toothbrush',
        image: 'https://images.unsplash.com/photo-1559599101-f09722fb4948?auto=format&fit=crop&q=80&w=800',
        description: 'Eco-friendly sonic vibration toothbrush with natural bamboo replaceable heads, 4 smart modes, and a charging case.',
        category: 'Wellness & Beauty',
        price: 65.00,
        stock: 60,
        rating: 4.7,
        numReviews: 49,
        user: vendor2Id,
      },
      {
        name: 'Hydrating Coconut Gel Lip Mask Set',
        image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&q=80&w=800',
        description: 'Deeply nourishes dry, chapped lips with standard vitamin E and pure cold-pressed coconut oil. Pack includes 12 individual gel patches.',
        category: 'Wellness & Beauty',
        price: 18.00,
        stock: 120,
        rating: 4.5,
        numReviews: 31,
        user: vendor2Id,
      },
      {
        name: 'Warm Soy Wax Therapeutic Massage Candle',
        image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=800',
        description: 'Light this beautiful candle, then pour the warm, skin-safe cosmetic soy wax directly onto skin for a luxury body massage treatment.',
        category: 'Wellness & Beauty',
        price: 28.00,
        stock: 50,
        rating: 4.8,
        numReviews: 29,
        user: vendor2Id,
      },
      {
        name: 'Lavender Fields Silk Soft Body Lotion',
        image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=800',
        description: 'Infused with calming French lavender essential oils, rich shea butter, and vitamin E to keep your skin deeply silky and soft.',
        category: 'Wellness & Beauty',
        price: 22.50,
        stock: 75,
        rating: 4.7,
        numReviews: 55,
        user: vendor2Id,
      }
    ];

    await Product.insertMany(sampleProducts);

    console.log('Data Seeded Successfully! Added 52 Premium Products across 5 categories.');
    process.exit();
  } catch (error) {
    console.error(`${error}`);
    process.exit(1);
  }
};

importData();
